<template>
    <div class="home">
        <div class="header">
            <div class="left">
                <div class="line">
                    <BlackBox></BlackBox>
                    <div class="text serif fw-b fs-l">Human Machine Collaboration</div>
                </div>
                <div class="line">
                    <BlackBox hasLine>FOR</BlackBox>
                    <div class="text serif fw-b fs-l">Calligraphy Restortaion</div>
                </div>
                <div class="line">
                    <BlackBox hasLine>WITH</BlackBox>
                    <div class="text serif fw-b fs-l">Crowdsourcing</div>
                </div>
            </div>
            <div class="middle">
                <Menu></Menu>
            </div>
            <div class="right"></div>
        </div>
        <div class="authors">
            <div class="left">
                <BlackBox style="visibility:hidden;"></BlackBox>
                <div class="content fs-s sans fw-m">
                    <a class="author" href="mailto:kxhan@zju.edu.cn">韩开鑫</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">尤伟涛</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">邓晃煌</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">孙凌云</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="mailto:songjinyu@zju.edu.cn">宋晋瑜</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">胡子衿</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">易和阳</a>
                </div>
            </div>

            <div class="right"></div>
        </div>
        <div class="intro">
            <div class="left">
                <BlackBox hasLine>INTRO</BlackBox>
                <div class="content">
                    <div
                        class="inner_text fw-r sans fs-s"
                    >Calligraphy is a valuable art form in many different cultures, there is a great need to repair damaged calligraphy manuscripts created in a very early period. Manual calligraphy restoration is time-consuming and relies heavily on professional skills. Automatic calligraphy restoration methods improve the efficiency of the manual process, but require massive data and ground truth for training and evaluation. To overcome the deficiencies of those methods, we present LanT, a human-machine collaboration system for calligraphy restoration with crowdsourcing. Through the tasks of crowdsourcing, we use expert knowledge to enhance the accuracy of characters segmentation, credibility of characters restoration, and reliability of characters evaluation. We applied our method to a famous Chinese calligraphy, and the results were evaluated in several perceptual studies, which showed that our characters evaluation had a high consistency with experts, and more experts preferred the restoration results of our method to those generated by other baseline methods.</div>
                </div>
            </div>

            <div class="right"></div>
        </div>
        <div class="demo">
            <div class="left">
                <BlackBox hasLine>DEMO</BlackBox>
                <div class="content">
                    <div class="origin">
                        <div class="title text fs-m">Damaged</div>
                        <img
                            src="../assets/broken.png"
                            alt="待修复图像"
                            style="object-fit: contain;width: 100%; height: auto;display: block;"
                        />
                    </div>
                    <div class="arrow">
                        <img
                            src="../assets/right1.png"
                            alt="right arrow"
                            style="width: 40%;  object-fit: contain; display: block; "
                        />
                    </div>
                    <div class="fixed">
                        <div class="title text fs-m">Restored</div>
                        <img
                            src="../assets/fixed.png"
                            alt="修复图像"
                            style="object-fit: contain; width: 100%; display: block;"
                        />
                    </div>
                </div>
            </div>
            <div class="right"></div>
        </div>
        <div class="moreinfo">
            <div class="text sans fs-r">
                For More Procedure Detail
                <router-link class="href" to="/procedure?index=001">&rarr;</router-link>
            </div>
        </div>
        <div class="acknowledgement">
            <div class="left"></div>
            <div class="content">
                <div class="title text fs-l" style="margin-bottom: 40px; text-transform: uppercase;font-family: DINCondensed-Bold;">Acknowledgement</div>
                <b style="margin-bottom: 80px;line-height: 24px;"> Thanks to experts, professors and students who provided valuable experimental data and guidance for Reasoning Lanting project (ranked in no particular order). They are Xianguang Qian, the director of art department of Tai'an and calligraphers and calligraphy lovers, Ziqiang Niu, Bin Wu, Rui Li, Shanshan Wang, Liang Zhang, Juhua Tang, Sheng Huang, Xuayu Song, Haishao Sun, Jieming Wang, Zhong Wang, Zirui Wang, Zhenjie Wang, Zengchao Wang, Zhengan Lu, Weian Li, Wenlin Huang, Chun Wu, Qier Zhang, Zhihong Tang.</b>
                <div class="title text fs-l serif fw-b" style="margin-bottom: 40px; text-transform: uppercase;">致谢</div>
                
                <b
                    style="line-height: 24px;"
                >感谢为《推理兰亭》课题提供宝贵实验数据和指导意见的各位专家、老师和同学（排名不分先后）。他们是泰安学院美术系主任钱先广，书法家和书法爱好者牛自强、吴斌、黄文龙、李瑞、王姗姗、张梁、唐菊华、黄生、宋璇毓、孙海哨、王洁敏、王仲、王子睿、王振杰、王增朝、卢峥安、李伟岸、黄雯琳、伍淳、张乞儿、汤志鸿等。</b>
            </div>
            <div class="right"></div>
        </div>
        <div class="footer">
            <div class="text sans fs-r">INLAB @ 2021</div>
        </div>
    </div>
</template>
<script setup lang='ts'>
import { onMounted } from '@vue/runtime-core'
import BlackBox from 'comps/BlackBox.vue'
import Menu from 'comps/Menu.vue'
import { useRouter } from 'vue-router'
const router = useRouter()
const createCharCell = () => {

}

const createTable = () => {

}
onMounted(() => {
    // 共60个字

})

const onRouter = (index: string) => {
    router.push({ path: '/procedure', query: { index } })
}

</script>
<style lang="scss" scoped>
.home {
    .header {
        width: 100%;
        display: flex;
        margin-top: 50px;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap column;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            .line {
                height: auto;
                display: flex;
                align-items: baseline;
                flex-flow: nowrap row;
                margin-bottom: 30px;

                .text {
                    height: auto;
                    line-height: 36px;
                }

                &:last-child {
                    margin-bottom: 0px;
                }
            }
        }

        .middle {
            flex: 1;
            display: flex;
            flex-direction: row-reverse;

            .menu {
                margin-top: 4px;
                width: 32px;
                height: min-content;

                .menu-line {
                    width: 32px;
                    height: 4px;
                    background-color: black;
                    margin-bottom: 6px;
                    transition: all 0.3s ease-in-out;
                    &:last-child {
                        margin-bottom: 0px;
                    }
                }

                &:hover {
                    cursor: pointer;
                    .menu-line {
                        transform: translateY(-2px);
                        box-shadow: 0px 2px 4px 1px rgba(0, 0, 0, 0.1);
                        // cursor: pointer;
                    }
                }
            }
        }

        .right {
            width: 10vw;
        }
    }

    .authors {
        width: 100%;
        display: flex;
        margin-top: 50px;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            .content {
                flex: 1;
                .author {
                    text-decoration: none;
                    color: black;
                    position: relative;
                    &::after {
                        content: "";
                        position: absolute;
                        bottom: -2px;
                        left: 0px;
                        width: 0%;
                        transition: width 0.3s ease-in-out;
                        height: 1px;
                        background-color: black;
                    }

                    &:hover {
                        &::after {
                            width: 100%;
                        }
                    }
                }
            }
        }

        .right {
            width: 10vw;
        }
    }

    .intro {
        width: 100%;
        display: flex;
        margin-top: 50px;
        position: relative;

        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            width: 90vw;
            .content {
                flex: 1;
                border: 2px solid black;
                box-sizing: border-box;
                padding: 20px 20px;
                // box-shadow: 0px 4px 8px 6px rgba(0, 0, 0, .1);

                .inner_text {
                    word-break: break-all;
                }
            }
        }

        .right {
            flex: 1;
        }
    }

    .demo {
        width: 100%;
        display: flex;
        flex-flow: nowrap row;
        margin-top: 50px;
        position: relative;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            width: 90vw;
            .content {
                display: flex;
                flex-flow: nowrap row;
                justify-content: center;
                align-items: center;
                flex: 1;
                width: calc(80vw - 15px);
                box-sizing: border-box;
                // border: 2px solid #000;
                background: #eee;
                padding: 40px 60px;
                position: relative;

                .origin,
                .fixed {
                    width: 45%;
                    box-sizing: border-box;
                    display: flex;
                    flex-flow: nowrap column;
                    align-items: center;
                    justify-content: flex-start;

                    .title {
                        padding-bottom: 5px;
                        font-family: DINCondensed-Bold;
                        user-select: none;
                        position: relative;
                        // font-weight: 800;
                        margin-bottom: 15px;

                        &:after {
                            content: "";
                            background-color: black;
                            width: 100%;
                            height: 4px;
                            position: absolute;
                            bottom: 0px;
                            left: 0px;
                        }
                    }
                    img {
                        border: 2px solid #000;
                        box-shadow: 0px 4px 12px 4px rgba(0, 0, 0, 0.1);
                    }
                }

                .arrow {
                    width: 10%;
                    // flex: 1;
                    // border: 2px solid #111;
                    box-sizing: border-box;
                    display: flex;
                    flex-flow: nowrap row;
                    justify-content: center;
                    align-items: center;
                    // height: 1000px;
                }
            }
        }

        .right {
            flex: 1;
        }
    }

    .acknowledgement {
        width: 100%;
        display: flex;
        flex-flow: nowrap row;
        margin-top: 50px;
        position: relative;
        margin-bottom: 100px;
        .left {
            width: calc(10vw + 15px);
        }
        .content {
            // height: 1000px;
            display: flex;
            width: calc(80vw - 15px);
            // width: 100%;
            flex-flow: nowrap column;
            justify-content: center;
            align-items: center;
            // border: 2px solid #000;
            padding: 100px 200px;
            box-sizing: border-box;
            box-shadow: 0px 4px 8px 6px rgba(0, 0, 0, .1);
        }

        .right {
            flex: 1;
        }
    }

    .moreinfo {
        width: 100%;
        height: 200px;
        margin-top: 50px;
        display: flex;
        flex-flow: nowrap row;
        justify-content: center;
        align-items: center;

        .text {
            user-select: none;
            .href {
                text-decoration: none;
                position: relative;
                color: black;
                // border-left: 1px solid;
                &::after {
                    content: "";
                    position: absolute;
                    width: 0%;
                    height: 2px;
                    background-color: black;
                    bottom: 0px;
                    left: 0px;
                    right: 0px;
                    transition: width 0.3s ease-in-out;
                }
                &:hover {
                    &::after {
                        width: 100%;
                    }
                }
            }
        }
    }

    .footer {
        width: 100%;
        height: 300px;
        margin-top: 50px;
        display: flex;
        flex-flow: nowrap row;
        justify-content: center;
        align-items: center;
        background-color: #000;
        color: white;

        .text {
        }
    }
}
</style>