<template>
    <div class="home">
        <div class="header">
            <div class="left">
                <div class="line">
                    <BlackBox></BlackBox>
                    <div class="text serif fw-b">Human Machine Collaboration</div>
                </div>
                <div class="line">
                    <BlackBox hasLine>FOR</BlackBox>
                    <div class="text serif fw-b">Calligraphy Restortaion</div>
                </div>
                <div class="line">
                    <BlackBox hasLine>WITH</BlackBox>
                    <div class="text serif fw-b">Crowdsourcing</div>
                </div>
            </div>
            <div class="middle">
                <div class="menu">
                    <div class="menu-line"></div>
                    <div class="menu-line"></div>
                    <div class="menu-line"></div>
                </div>
            </div>
            <div class="right"></div>
        </div>
        <div class="authors">
            <div class="left">
                <BlackBox style="visibility:hidden;"></BlackBox>
                <div class="content sans fw-m">
                    <a class="author" href="#">韩开鑫</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">尤伟涛</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">邓煌煌</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">孙凌云</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">宋晋瑜</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">胡子衿</a>
                    <span class="sep">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <a class="author" href="#">易和阳</a>
                </div>
            </div>

            <div class="right"></div>
        </div>
        <div class="intro">
            <div class="left">
                <BlackBox hasLine>INTRO</BlackBox>
                <div class="content">
                    <div
                        class="inner_text fw-r sans"
                    >
                    Calligraphy is a valuable art form in many different cultures, there is a great need to repair damaged calligraphy manuscripts created in a very early period. Manual calligraphy restoration is time-consuming and relies heavily on professional skills. Automatic calligraphy restoration methods improve the efficiency of the manual process, but require massive data and ground truth for training and evaluation. To overcome the deficiencies of those methods, we present LanT, a human-machine collaboration system for calligraphy restoration with crowdsourcing. Through the tasks of crowdsourcing, we use expert knowledge to enhance the accuracy of characters segmentation, credibility of characters restoration, and reliability of characters evaluation. We applied our method to a famous Chinese calligraphy, and the results were evaluated in several perceptual studies, which showed that our characters evaluation had a high consistency with experts, and more experts preferred the restoration results of our method to those generated by other baseline methods.
                    </div>
                </div>
            </div>

            <div class="right"></div>
        </div>
        <div class="demo">
            <div class="left">
                <BlackBox hasLine>DEMO</BlackBox>
                <div class="content">
                    <div class="origin">
                        <div class="title">Origin</div>
                        <div class="chars_box"></div>
                    </div>
                    <div class="origin">
                        <div class="title">Origin</div>
                        <div class="chars_box"></div>
                    </div>
                </div>
            </div>
            <div class="right"></div>
        </div>
        <div class="moreinfo"></div>
        <div class="footer"></div>
    </div>
</template>
<script setup lang='ts'>
import BlackBox from 'comps/BlackBox.vue'
</script>
<style lang="scss" scoped>
.home {
    .header {
        width: 100%;
        display: flex;
        margin-top: 50px;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap column;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            .line {
                height: auto;
                display: flex;
                align-items: baseline;
                flex-flow: nowrap row;
                margin-bottom: 30px;

                .text {
                    font-size: 40px;
                    height: auto;
                    line-height: 36px;
                }

                &:last-child {
                    margin-bottom: 0px;
                }
            }
        }

        .middle {
            flex: 1;
            display: flex;
            flex-direction: row-reverse;

            .menu {
                margin-top: 4px;
                width: 32px;
                height: min-content;

                .menu-line {
                    width: 32px;
                    height: 4px;
                    background-color: black;
                    margin-bottom: 6px;
                    transition: all 0.3s ease-in-out;
                    &:last-child {
                        margin-bottom: 0px;
                    }
                }

                &:hover {
                    cursor: pointer;
                    .menu-line {
                        transform: translateY(-2px);
                        box-shadow: 0px 2px 4px 1px rgba(0, 0, 0, 0.1);
                        // cursor: pointer;
                    }
                }
            }
        }

        .right {
            width: 10vw;
        }
    }

    .authors {
        width: 100%;
        display: flex;
        margin-top: 50px;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            .content {
                flex: 1;
                .author {
                    text-decoration: none;
                    color: black;
                    position: relative;
                    &::after {
                        content: "";
                        position: absolute;
                        bottom: -2px;
                        left: 0px;
                        width: 0%;
                        transition: width 0.3s ease-in-out;
                        height: 1px;
                        background-color: black;
                    }

                    &:hover {
                        &::after {
                            width: 100%;
                        }
                    }
                }
            }
        }

        .right {
            width: 10vw;
        }
    }

    .intro {
        width: 100%;
        display: flex;
        margin-top: 50px;
        position: relative;

        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            width: 90vw;
            .content {
                flex: 1;
                border: 2px solid black;
                box-sizing: border-box;
                padding: 20px 20px;

                .inner_text {
                    word-break: break-all;
                    font-size: 20px;
                }
            }
        }

        .right {
            flex: 1;
        }
    }

    .demo {
        width: 100%;
        display: flex;
        flex-flow: nowrap row;
        margin-top: 50px;
        position: relative;
        .left {
            position: relative;
            display: flex;
            flex-flow: nowrap row;
            justify-content: flex-start;
            align-items: flex-start;
            height: auto;
            width: 90vw;
            .content {
                display: flex;
                flex-flow: nowrap row;
                justify-content: flex-start;
                align-items: flex-start;

                .origin {
                    display: flex;
                    flex-flow: nowrap column;
                    justify-content: flex-start;
                    align-items: flex-start;
                    margin-right: 15px;;

                    .chars_box {
                        border: 2px solid #000;
                        height: 100px;
                        width: 400px;
                    }
                }
            }
        }

        .right {
            flex: 1;
        }
    }
}
</style>